export const CHECK_NIKKSWP_START = 'act/CHECK_NIKKSWP_START'
export const LOGIN_SUCCESS = 'act/LOGIN_SUCCESS'
export const CHECK_TOKEN_SUCCESS = 'act/CHECK_TOKEN_SUCCESS'
export const LOGOUT_SUCCESS = 'act/LOGOUT_SUCCESS'
